export const INCREMENT_SCORE = "INCREMENT_SCORE"

export const INCREASE_FITTS_SCORE = "INCREASE_FITTS_SCORE"

export const PICK_A_NEW_HIGHLIGHT = "PICK_A_NEW_HIGHLIGHT"

export const PICK_THREE_RANDOM_TILES = "PICK_THREE_RANDOM_TILES"

export const UPDATE_PREV_X_Y_COORD = "UPDATE_PREV_X_Y_COORD"

export const RESET_GAME = "RESET_GAME"

export const SET_TIME = "SET_TIME"